namespace CarbonCore.Modules.D3Theory.Logic.Enums
{
    using System.Collections.Generic;
    
    using CarbonCore.Utils;
    
    public static class EnumValues
    {
        // -------------------------------------------------------------------
        // Auto Generated by EnumValues.tt DO NOT MODIFY DIRECTLY!
        // -------------------------------------------------------------------
        public static readonly IReadOnlyCollection<D3Attribute> D3AttributeValues = EnumExtensions.GetValues<D3Attribute>();

        public static readonly IReadOnlyCollection<D3DamageType> D3DamageTypeValues = EnumExtensions.GetValues<D3DamageType>();

        public static readonly IReadOnlyCollection<D3EntityAttribute> D3EntityAttributeValues = EnumExtensions.GetValues<D3EntityAttribute>();

        public static readonly IReadOnlyCollection<D3GearType> D3GearTypeValues = EnumExtensions.GetValues<D3GearType>();

        public static readonly IReadOnlyCollection<D3SkillAttribute> D3SkillAttributeValues = EnumExtensions.GetValues<D3SkillAttribute>();

        public static readonly IReadOnlyCollection<SimulationStat> SimulationStatValues = EnumExtensions.GetValues<SimulationStat>();

    }
}